// Jedi.swift

import Foundation

// The below type is accessible to Objective-C via its `@objc` attribute,
// `public` access, and subclassing of `NSObject`
@objcMembers public class Jedi: NSObject {
    public let name: String

    public init(name: String) {
        self.name = name
    }

    // Returns `true` if this Jedi wins against the given Sith; otherwise, `false`.
    // Note that the `Sith` is declared by the Objective-C half of the target.
    public func duel(sith: Sith) -> Bool {
        // Only Master Yoda can defeat the Sith.
        if self.name == "Yoda" {
            // We print using the C function defined in droid_debug.h.
            DROID_DEBUG(
                "Master Jedi \(self.name) defeated Sith Lord \(sith.name)"
            );
            return true
        } else {
            // We print using the C function defined in droid_debug.h.
            DROID_DEBUG(
                "Sith Lord \(sith.name) defeated Master Jedi \(self.name)"
            );
            return false
        }
    }

    // Access target's resource bundle.
    public func readAncientJediTexts() throws -> String {
        // The `Bundle.module` is generated by SwiftPM to provide access to the
        // target's bundled resources.
        let path = Bundle.module.path(forResource: "hello_there", ofType: "txt")
        let contents = try String(contentsOfFile: path!, encoding: .utf8)
        return contents
    }
}
